"""Change Int to Float

Revision ID: a661036b4417
Revises: 695c2606dfbe
Create Date: 2023-11-03 08:50:37.496812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a661036b4417'
down_revision = '695c2606dfbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
